theme: jekyll-theme-minimal
title: Kateura's Homepage
description: Bookmark this to keep an eye on my project updates!
title: Unity Zelda Dungeon - By Keaton
title: https://kateura.itch.io/zelda-dungeon-snippet
description: Using Unity and C#, I developed tha majority of the weapons and Enemy AIs. I also created a duplication mechanic in which link can create weaker copies of himself. I experimented with audio in creating the sound effect for the switches, alongside art in creating all of the custom sprites.
